# Generated by Django 5.1.4 on 2025-01-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_user_email_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('cpu', 'CPU'), ('ram', 'RAM'), ('gpu', 'GPU'), ('ssd', 'SSD'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('keyboard', 'Keyboard')], max_length=50)),
                ('product_image', models.URLField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
